ENTITIES = [
    {"name": "Нефть", "type": "commodity", "aliases": ["нефть", "Brent", "марка Brent", "Urals"]},
    {"name": "Топливо", "type": "commodity", "aliases": ["керосин", "топливо", "авиатопливо", "авиакеросин"]},
    {"name": "Природный газ", "type": "commodity", "aliases": ["газ", "природный газ"]},
    {"name": "Золото", "type": "commodity", "aliases": ["золото"]},
    {"name": "Уголь", "type": "commodity", "aliases": ["уголь", "коксующийся уголь"]},
    {"name": "Сталь", "type": "commodity", "aliases": ["сталь", "прокат", "чёрные металлы"]},
    {"name": "Железная руда", "type": "commodity", "aliases": ["железная руда", "руда"]},
    {"name": "Алюминий", "type": "commodity", "aliases": ["алюминий"]},
    {"name": "Никель", "type": "commodity", "aliases": ["никель"]},
    {"name": "Медь", "type": "commodity", "aliases": ["медь"]},
    {"name": "Палладий", "type": "commodity", "aliases": ["палладий"]},
    {"name": "Удобрения", "type": "commodity", "aliases": ["удобрения", "минеральные удобрения"]},
    {"name": "Доллар США", "type": "currency", "aliases": ["доллар", "USD", "USD/RUB"]},
    {"name": "Евро", "type": "currency", "aliases": ["евро", "EUR", "EUR/RUB"]},
    {"name": "Юань", "type": "currency", "aliases": ["юань", "CNY", "CNY/RUB"]},
    {"name": "Рубль", "type": "currency", "aliases": ["рубль", "RUB"]},
    {"name": "Ключевая ставка ЦБ", "type": "macro_indicator", "aliases": ["ключевая ставка", "ставка ЦБ", "ставка Банка России"]},
    {"name": "Инфляция", "type": "macro_indicator", "aliases": ["инфляция", "ИПЦ", "индекс потребительских цен"]},
    {"name": "Индекс деловой активности (PMI)", "type": "macro_indicator", "aliases": ["PMI", "индекс деловой активности", "промпроизводство"]},
    {"name": "ВВП России", "type": "macro_indicator", "aliases": ["ВВП", "валовой внутренний продукт"]},
    {"name": "Потребительский спрос", "type": "macro_indicator", "aliases": ["потребительский спрос", "реальные доходы", "потребление"]},
    {"name": "Геополитический риск", "type": "event", "aliases": ["геополитический риск", "геополитика", "напряжённость"]},
    {"name": "Санкции", "type": "event", "aliases": ["санкции", "санкционное давление"]},
    {"name": "Индекс МосБиржи", "type": "index", "aliases": ["MOEX", "индекс Мосбиржи", "IMOEX"]},
    {"name": "Индекс RTS", "type": "index", "aliases": ["RTS", "индекс РТС"]},
    {"name": "Авиаперевозки", "type": "sector", "aliases": ["авиация", "авиаперевозки", "авиаотрасль"]},
    {"name": "Нефтегазовый сектор", "type": "sector", "aliases": ["нефтегазовый сектор", "нефтянка", "нефтегаз"]},
    {"name": "Банковский сектор", "type": "sector", "aliases": ["банки", "банковский сектор"]},
    {"name": "Металлургия", "type": "sector", "aliases": ["металлургия", "металлурги", "чёрная металлургия"]},
    {"name": "Цветная металлургия", "type": "sector", "aliases": ["цветная металлургия", "цветные металлы"]},
    {"name": "Добыча драгметаллов", "type": "sector", "aliases": ["золотодобыча", "драгметаллы", "золотодобытчики"]},
    {"name": "Угольная отрасль", "type": "sector", "aliases": ["угольная отрасль", "углепром", "угольщики"]},
    {"name": "Электроэнергетика", "type": "sector", "aliases": ["электроэнергетика", "генерация", "энергетики"]},
    {"name": "Технологии", "type": "sector", "aliases": ["технологии", "ИТ", "IT-сектор", "интернет-компании"]},
    {"name": "Ритейл", "type": "sector", "aliases": ["ритейл", "розничная торговля", "ретейл"]},
    {"name": "Химическая промышленность", "type": "sector", "aliases": ["химическая промышленность", "химпром", "химия"]},
    {"name": "Телеком", "type": "sector", "aliases": ["телеком", "связь", "телекоммуникации"]},
    {"name": "Девелопмент", "type": "sector", "aliases": ["девелопмент", "застройщики", "строительство жилья", "недвижимость"]},
    {"name": "Транспорт", "type": "sector", "aliases": ["транспорт", "перевозки", "логистика"]},
    {"name": "Автопром", "type": "sector", "aliases": ["автопром", "автопроизводители", "автомобильная промышленность"]},
    {"name": "Аэрофлот", "type": "company", "aliases": ["Аэрофлот", "ПАО Аэрофлот", "AFLT"]},
    {"name": "Лукойл", "type": "company", "aliases": ["Лукойл", "ЛУКОЙЛ", "LKOH"]},
    {"name": "Газпром", "type": "company", "aliases": ["Газпром", "GAZP"]},
    {"name": "Сбербанк", "type": "company", "aliases": ["Сбер", "Сбербанк", "SBER"]},
    {"name": "НЛМК", "type": "company", "aliases": ["НЛМК", "NLMK"]},
    {"name": "Северсталь", "type": "company", "aliases": ["Северсталь", "CHMF"]},
    {"name": "ММК", "type": "company", "aliases": ["ММК", "MAGN"]},
    {"name": "Полюс", "type": "company", "aliases": ["Полюс", "Полюс Золото", "PLZL"]},
    {"name": "Норникель", "type": "company", "aliases": ["Норникель", "ГМК Норникель", "GMKN"]},
    {"name": "Русал", "type": "company", "aliases": ["Русал", "РУСАЛ", "RUAL"]},
    {"name": "Интер РАО", "type": "company", "aliases": ["Интер РАО", "Inter RAO", "IRAO"]},
    {"name": "РусГидро", "type": "company", "aliases": ["РусГидро", "HYDR"]},
    {"name": "Яндекс", "type": "company", "aliases": ["Яндекс", "Yandex", "YDEX"]},
    {"name": "VK", "type": "company", "aliases": ["VK", "VKCO", "ВК"]},
    {"name": "Магнит", "type": "company", "aliases": ["Магнит", "MGNT"]},
    {"name": "X5 Group", "type": "company", "aliases": ["X5 Group", "X5", "Пятёрочка", "Перекрёсток", "FIVE"]},
    {"name": "Ozon", "type": "company", "aliases": ["Ozon", "OZON", "Озон"]},
    {"name": "Фосагро", "type": "company", "aliases": ["Фосагро", "PhosAgro", "PHOR"]},
    {"name": "Уралкалий", "type": "company", "aliases": ["Уралкалий", "Uralkali", "URKA"]},
    {"name": "Акрон", "type": "company", "aliases": ["Акрон", "AKRN"]},
    {"name": "МТС", "type": "company", "aliases": ["МТС", "MTS", "MTSS"]},
    {"name": "Ростелеком", "type": "company", "aliases": ["Ростелеком", "RTKM"]},
    {"name": "ПИК", "type": "company", "aliases": ["ПИК", "ПИК-группа", "PIKK"]},
    {"name": "ЛСР", "type": "company", "aliases": ["ЛСР", "LSRG"]},
    {"name": "Транснефть", "type": "company", "aliases": ["Транснефть", "TRNFP"]},
    {"name": "Globaltrans", "type": "company", "aliases": ["Globaltrans", "Глобалтранс", "GLTR"]},
    {"name": "АвтоВАЗ", "type": "company", "aliases": ["АвтоВАЗ", "LADA", "AVAZ"]},
    {"name": "КамАЗ", "type": "company", "aliases": ["КамАЗ", "KAMAZ", "KMAZ"]},
    {"name": "Мечел", "type": "company", "aliases": ["Мечел", "MTLR"]},
    {"name": "Распадская", "type": "company", "aliases": ["Распадская", "RASP"]},
]

INFLUENCES = [
    {"from": "Нефть", "to": "Топливо", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Сырая нефть — основное сырьё для производства топлива и керосина; рост нефти напрямую удорожает топливо.", "source_ref": "curated"},
    {"from": "Топливо", "to": "Авиаперевозки", "direction": "negative", "strength": "strong", "kind": "direct", "confidence": 0.85, "rationale": "Авиатопливо — крупнейшая статья операционных издержек авиакомпаний; рост цен на топливо снижает маржинальность.", "source_ref": "curated"},
    {"from": "Нефть", "to": "Авиаперевозки", "direction": "negative", "strength": "medium", "kind": "indirect", "confidence": 0.7, "rationale": "Косвенная цепочка: нефть → топливо → издержки авиакомпаний.", "source_ref": "curated"},
    {"from": "Нефть", "to": "Нефтегазовый сектор", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Выручка нефтегазовых компаний напрямую зависит от цен на сырьё.", "source_ref": "curated"},
    {"from": "Природный газ", "to": "Нефтегазовый сектор", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.8, "rationale": "Газ — второй по значимости продукт сектора после нефти.", "source_ref": "curated"},
    {"from": "Нефтегазовый сектор", "to": "Лукойл", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Лукойл — одна из крупнейших нефтедобывающих компаний РФ.", "source_ref": "curated"},
    {"from": "Нефтегазовый сектор", "to": "Газпром", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.85, "rationale": "Газпром — системообразующая компания сектора; цена на газ коррелирует с энергетическим рынком.", "source_ref": "curated"},
    {"from": "Авиаперевозки", "to": "Аэрофлот", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Аэрофлот — флагманский авиаперевозчик России, напрямую зависит от состояния отрасли.", "source_ref": "curated"},
    {"from": "Рубль", "to": "Авиаперевозки", "direction": "negative", "strength": "medium", "kind": "indirect", "confidence": 0.6, "rationale": "Девальвация рубля удорожает лизинг, обслуживание иностранных самолётов и зарубежную логистику.", "source_ref": "curated"},
    {"from": "Рубль", "to": "Нефтегазовый сектор", "direction": "positive", "strength": "medium", "kind": "indirect", "confidence": 0.65, "rationale": "Выручка экспортёров в валюте, расходы частично в рублях: слабый рубль повышает рублёвую прибыль.", "source_ref": "curated"},
    {"from": "Доллар США", "to": "Рубль", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Рост доллара ослабляет рубль (курс USD/RUB растёт).", "source_ref": "curated"},
    {"from": "Евро", "to": "Рубль", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Рост евро ослабляет рубль (курс EUR/RUB растёт).", "source_ref": "curated"},
    {"from": "Юань", "to": "Рубль", "direction": "positive", "strength": "medium", "kind": "direct", "confidence": 0.6, "rationale": "Рост юаня ослабляет рубль (курс CNY/RUB растёт).", "source_ref": "curated"},
    {"from": "Нефть", "to": "Рубль", "direction": "positive", "strength": "strong", "kind": "indirect", "confidence": 0.7, "rationale": "Дорогая нефть наращивает экспортную выручку и укрепляет рубль.", "source_ref": "curated"},
    {"from": "Ключевая ставка ЦБ", "to": "Рубль", "direction": "positive", "strength": "strong", "kind": "indirect", "confidence": 0.7, "rationale": "Высокие ставки привлекают капитал и укрепляют валюту.", "source_ref": "curated"},
    {"from": "Рубль", "to": "Инфляция", "direction": "negative", "strength": "medium", "kind": "indirect", "confidence": 0.7, "rationale": "Укрепление рубля удешевляет импорт и снижает инфляционное давление.", "source_ref": "curated"},
    {"from": "Доллар США", "to": "Инфляция", "direction": "positive", "strength": "medium", "kind": "indirect", "confidence": 0.6, "rationale": "Слабый рубль удорожает импорт и разгоняет инфляцию.", "source_ref": "curated"},
    {"from": "Инфляция", "to": "Ключевая ставка ЦБ", "direction": "positive", "strength": "medium", "kind": "indirect", "confidence": 0.8, "rationale": "Рост инфляции провоцирует ужесточение денежно-кредитной политики.", "source_ref": "curated"},
    {"from": "Ключевая ставка ЦБ", "to": "Банковский сектор", "direction": "positive", "strength": "medium", "kind": "indirect", "confidence": 0.6, "rationale": "Высокие ставки расширяют чистую процентную маржу банков.", "source_ref": "curated"},
    {"from": "Ключевая ставка ЦБ", "to": "Авиаперевозки", "direction": "negative", "strength": "medium", "kind": "indirect", "confidence": 0.55, "rationale": "Высокие ставки удорожают кредитное финансирование и лизинг самолётов.", "source_ref": "curated"},
    {"from": "Ключевая ставка ЦБ", "to": "Индекс МосБиржи", "direction": "negative", "strength": "medium", "kind": "indirect", "confidence": 0.7, "rationale": "Дорогие деньги давят на оценку акций в целом.", "source_ref": "curated"},
    {"from": "Ключевая ставка ЦБ", "to": "Девелопмент", "direction": "negative", "strength": "strong", "kind": "indirect", "confidence": 0.7, "rationale": "Рост ставок удорожает ипотеку и снижает спрос на жильё.", "source_ref": "curated"},
    {"from": "Ключевая ставка ЦБ", "to": "Ритейл", "direction": "negative", "strength": "medium", "kind": "indirect", "confidence": 0.6, "rationale": "Дорогие кредиты охлаждают потребительский спрос.", "source_ref": "curated"},
    {"from": "Ключевая ставка ЦБ", "to": "Автопром", "direction": "negative", "strength": "medium", "kind": "indirect", "confidence": 0.6, "rationale": "Дорогие автокредиты снижают спрос на автомобили.", "source_ref": "curated"},
    {"from": "Ключевая ставка ЦБ", "to": "Технологии", "direction": "negative", "strength": "strong", "kind": "indirect", "confidence": 0.7, "rationale": "Growth-акции наиболее чувствительны к стоимости капитала.", "source_ref": "curated"},
    {"from": "Банковский сектор", "to": "Сбербанк", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Сбербанк — крупнейший банк России, ключевой представитель сектора.", "source_ref": "curated"},
    {"from": "Рубль", "to": "Металлургия", "direction": "positive", "strength": "medium", "kind": "indirect", "confidence": 0.6, "rationale": "Металлурги — экспортёры: слабый рубль повышает рублёвую выручку.", "source_ref": "curated"},
    {"from": "Рубль", "to": "Цветная металлургия", "direction": "positive", "strength": "medium", "kind": "indirect", "confidence": 0.6, "rationale": "Цветные металлы экспортируются: слабый рубль выгоден производителям.", "source_ref": "curated"},
    {"from": "Рубль", "to": "Угольная отрасль", "direction": "positive", "strength": "medium", "kind": "indirect", "confidence": 0.6, "rationale": "Угольщики ориентированы на экспорт: слабый рубль повышает рублёвую выручку.", "source_ref": "curated"},
    {"from": "Сталь", "to": "Металлургия", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Сталь — основной продукт отрасли.", "source_ref": "curated"},
    {"from": "Железная руда", "to": "Сталь", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.85, "rationale": "Железная руда — главное сырьё для выплавки стали.", "source_ref": "curated"},
    {"from": "Уголь", "to": "Сталь", "direction": "positive", "strength": "medium", "kind": "direct", "confidence": 0.6, "rationale": "Коксующийся уголь используется в металлургии.", "source_ref": "curated"},
    {"from": "Металлургия", "to": "НЛМК", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "НЛМК — крупный производитель стали.", "source_ref": "curated"},
    {"from": "Металлургия", "to": "Северсталь", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Северсталь — крупный производитель стали.", "source_ref": "curated"},
    {"from": "Металлургия", "to": "ММК", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "ММК — крупный производитель стали.", "source_ref": "curated"},
    {"from": "Металлургия", "to": "Индекс МосБиржи", "direction": "positive", "strength": "medium", "kind": "indirect", "confidence": 0.7, "rationale": "Металлургия — весомая часть индекса.", "source_ref": "curated"},
    {"from": "Алюминий", "to": "Цветная металлургия", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Алюминий — базовый цветной металл.", "source_ref": "curated"},
    {"from": "Никель", "to": "Цветная металлургия", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Никель — базовый цветной металл.", "source_ref": "curated"},
    {"from": "Медь", "to": "Цветная металлургия", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.85, "rationale": "Медь — базовый цветной металл, индикатор экономики.", "source_ref": "curated"},
    {"from": "Палладий", "to": "Норникель", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.8, "rationale": "Норникель — крупнейший мировой производитель палладия.", "source_ref": "curated"},
    {"from": "Цветная металлургия", "to": "Норникель", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Норникель — лидер цветной металлургии России.", "source_ref": "curated"},
    {"from": "Цветная металлургия", "to": "Русал", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Русал — крупнейший производитель алюминия.", "source_ref": "curated"},
    {"from": "Цветная металлургия", "to": "Индекс МосБиржи", "direction": "positive", "strength": "medium", "kind": "indirect", "confidence": 0.6, "rationale": "Цветные металлурги входят в индекс.", "source_ref": "curated"},
    {"from": "Золото", "to": "Добыча драгметаллов", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Золото — основной продукт золотодобычи.", "source_ref": "curated"},
    {"from": "Доллар США", "to": "Золото", "direction": "negative", "strength": "weak", "kind": "indirect", "confidence": 0.5, "rationale": "Сильный доллар обычно давит на цену золота.", "source_ref": "curated"},
    {"from": "Добыча драгметаллов", "to": "Полюс", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Полюс — крупнейший золотодобытчик России.", "source_ref": "curated"},
    {"from": "Уголь", "to": "Угольная отрасль", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Цены на уголь определяют выручку отрасли.", "source_ref": "curated"},
    {"from": "Угольная отрасль", "to": "Мечел", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.85, "rationale": "Мечел — крупный угледобытчик.", "source_ref": "curated"},
    {"from": "Угольная отрасль", "to": "Распадская", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.85, "rationale": "Распадская — производитель коксующегося угля.", "source_ref": "curated"},
    {"from": "Электроэнергетика", "to": "Интер РАО", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Интер РАО — крупный игрок электроэнергетики и экспорта энергии.", "source_ref": "curated"},
    {"from": "Электроэнергетика", "to": "РусГидро", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "РусГидро — крупнейший гидрогенератор России.", "source_ref": "curated"},
    {"from": "Электроэнергетика", "to": "Индекс МосБиржи", "direction": "positive", "strength": "weak", "kind": "indirect", "confidence": 0.5, "rationale": "Энергетики входят в индекс.", "source_ref": "curated"},
    {"from": "Технологии", "to": "Яндекс", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Яндекс — ведущая ИТ-компания России.", "source_ref": "curated"},
    {"from": "Технологии", "to": "VK", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "VK — крупная интернет-платформа.", "source_ref": "curated"},
    {"from": "Технологии", "to": "Индекс МосБиржи", "direction": "positive", "strength": "medium", "kind": "indirect", "confidence": 0.7, "rationale": "ИТ-компании входят в индекс.", "source_ref": "curated"},
    {"from": "Потребительский спрос", "to": "Ритейл", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.8, "rationale": "Выручка ритейла напрямую зависит от потребительского спроса.", "source_ref": "curated"},
    {"from": "Ритейл", "to": "Магнит", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Магнит — крупнейшая сеть продуктового ритейла.", "source_ref": "curated"},
    {"from": "Ритейл", "to": "X5 Group", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "X5 Group — лидер продуктового ритейла (Пятёрочка, Перекрёсток).", "source_ref": "curated"},
    {"from": "Ритейл", "to": "Ozon", "direction": "positive", "strength": "medium", "kind": "direct", "confidence": 0.8, "rationale": "Ozon — крупный e-commerce и маркетплейс.", "source_ref": "curated"},
    {"from": "Ритейл", "to": "Индекс МосБиржи", "direction": "positive", "strength": "weak", "kind": "indirect", "confidence": 0.5, "rationale": "Ритейлеры входят в индекс.", "source_ref": "curated"},
    {"from": "Удобрения", "to": "Химическая промышленность", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.8, "rationale": "Удобрения — ключевой продукт химической отрасли.", "source_ref": "curated"},
    {"from": "Химическая промышленность", "to": "Фосагро", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Фосагро — производитель фосфорных удобрений.", "source_ref": "curated"},
    {"from": "Химическая промышленность", "to": "Уралкалий", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Уралкалий — производитель калийных удобрений.", "source_ref": "curated"},
    {"from": "Химическая промышленность", "to": "Акрон", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Акрон — производитель минеральных удобрений.", "source_ref": "curated"},
    {"from": "Химическая промышленность", "to": "Индекс МосБиржи", "direction": "positive", "strength": "weak", "kind": "indirect", "confidence": 0.5, "rationale": "Химики входят в индекс.", "source_ref": "curated"},
    {"from": "Телеком", "to": "МТС", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "МТС — крупнейший оператор связи.", "source_ref": "curated"},
    {"from": "Телеком", "to": "Ростелеком", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Ростелеком — национальный оператор связи.", "source_ref": "curated"},
    {"from": "Девелопмент", "to": "ПИК", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "ПИК — крупнейший девелопер жилья.", "source_ref": "curated"},
    {"from": "Девелопмент", "to": "ЛСР", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "ЛСР — крупный девелопер.", "source_ref": "curated"},
    {"from": "Транспорт", "to": "Транснефть", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Транснефть — оператор магистральных нефтепроводов.", "source_ref": "curated"},
    {"from": "Транспорт", "to": "Globaltrans", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "Globaltrans — крупный железнодорожный перевозчик.", "source_ref": "curated"},
    {"from": "Нефтегазовый сектор", "to": "Транспорт", "direction": "positive", "strength": "medium", "kind": "indirect", "confidence": 0.6, "rationale": "Объёмы прокачки нефти формируют спрос на транспорт.", "source_ref": "curated"},
    {"from": "Автопром", "to": "АвтоВАЗ", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "АвтоВАЗ — крупнейший автопроизводитель России.", "source_ref": "curated"},
    {"from": "Автопром", "to": "КамАЗ", "direction": "positive", "strength": "strong", "kind": "direct", "confidence": 0.9, "rationale": "КамАЗ — крупный производитель грузовиков.", "source_ref": "curated"},
    {"from": "Нефтегазовый сектор", "to": "Индекс МосБиржи", "direction": "positive", "strength": "medium", "kind": "indirect", "confidence": 0.8, "rationale": "Нефтегаз — крупнейшая доля индекса МосБиржи по капитализации.", "source_ref": "curated"},
    {"from": "Банковский сектор", "to": "Индекс МосБиржи", "direction": "positive", "strength": "medium", "kind": "indirect", "confidence": 0.7, "rationale": "Банки — весомая часть индекса МосБиржи.", "source_ref": "curated"},
    {"from": "Индекс деловой активности (PMI)", "to": "Индекс МосБиржи", "direction": "positive", "strength": "weak", "kind": "indirect", "confidence": 0.6, "rationale": "Рост деловой активности поддерживает рынок акций.", "source_ref": "curated"},
    {"from": "ВВП России", "to": "Индекс МосБиржи", "direction": "positive", "strength": "medium", "kind": "indirect", "confidence": 0.6, "rationale": "Рост экономики поддерживает рынок акций.", "source_ref": "curated"},
    {"from": "Потребительский спрос", "to": "Индекс МосБиржи", "direction": "positive", "strength": "weak", "kind": "indirect", "confidence": 0.4, "rationale": "Потребление поддерживает широкий рынок.", "source_ref": "curated"},
    {"from": "Доллар США", "to": "Индекс RTS", "direction": "positive", "strength": "medium", "kind": "direct", "confidence": 0.7, "rationale": "Индекс RTS считается в долларах: слабый рубль повышает его значение.", "source_ref": "curated"},
    {"from": "Геополитический риск", "to": "Рубль", "direction": "negative", "strength": "strong", "kind": "indirect", "confidence": 0.7, "rationale": "Рост напряжённости ослабляет рубль (отток капитала).", "source_ref": "curated"},
    {"from": "Геополитический риск", "to": "Золото", "direction": "positive", "strength": "medium", "kind": "indirect", "confidence": 0.6, "rationale": "Золото — защитный актив при росте рисков.", "source_ref": "curated"},
    {"from": "Геополитический риск", "to": "Индекс МосБиржи", "direction": "negative", "strength": "strong", "kind": "indirect", "confidence": 0.7, "rationale": "Геополитика давит на российский рынок акций.", "source_ref": "curated"},
    {"from": "Санкции", "to": "Рубль", "direction": "negative", "strength": "strong", "kind": "indirect", "confidence": 0.7, "rationale": "Санкционное давление ослабляет рубль.", "source_ref": "curated"},
    {"from": "Санкции", "to": "Индекс МосБиржи", "direction": "negative", "strength": "strong", "kind": "indirect", "confidence": 0.7, "rationale": "Санкции давят на российский рынок.", "source_ref": "curated"},
]

SECURITIES = [
    {"ticker": "AFLT", "name": "Аэрофлот", "market": "MOEX", "security_type": "stock", "sector": "Авиаперевозки", "currency": "RUB", "aliases": ["ПАО Аэрофлот", "Аэрофлот"]},
    {"ticker": "LKOH", "name": "Лукойл", "market": "MOEX", "security_type": "stock", "sector": "Нефтегазовый сектор", "currency": "RUB", "aliases": ["ЛУКОЙЛ", "Лукойл"]},
    {"ticker": "GAZP", "name": "Газпром", "market": "MOEX", "security_type": "stock", "sector": "Нефтегазовый сектор", "currency": "RUB", "aliases": ["Газпром"]},
    {"ticker": "SBER", "name": "Сбербанк", "market": "MOEX", "security_type": "stock", "sector": "Банковский сектор", "currency": "RUB", "aliases": ["Сбер", "Сбербанк"]},
    {"ticker": "NLMK", "name": "НЛМК", "market": "MOEX", "security_type": "stock", "sector": "Металлургия", "currency": "RUB", "aliases": ["НЛМК"]},
    {"ticker": "CHMF", "name": "Северсталь", "market": "MOEX", "security_type": "stock", "sector": "Металлургия", "currency": "RUB", "aliases": ["Северсталь"]},
    {"ticker": "MAGN", "name": "ММК", "market": "MOEX", "security_type": "stock", "sector": "Металлургия", "currency": "RUB", "aliases": ["ММК"]},
    {"ticker": "PLZL", "name": "Полюс", "market": "MOEX", "security_type": "stock", "sector": "Добыча драгметаллов", "currency": "RUB", "aliases": ["Полюс", "Полюс Золото"]},
    {"ticker": "GMKN", "name": "Норникель", "market": "MOEX", "security_type": "stock", "sector": "Цветная металлургия", "currency": "RUB", "aliases": ["ГМК Норникель", "Норникель"]},
    {"ticker": "RUAL", "name": "Русал", "market": "MOEX", "security_type": "stock", "sector": "Цветная металлургия", "currency": "RUB", "aliases": ["РУСАЛ", "Русал"]},
    {"ticker": "IRAO", "name": "Интер РАО", "market": "MOEX", "security_type": "stock", "sector": "Электроэнергетика", "currency": "RUB", "aliases": ["Интер РАО"]},
    {"ticker": "HYDR", "name": "РусГидро", "market": "MOEX", "security_type": "stock", "sector": "Электроэнергетика", "currency": "RUB", "aliases": ["РусГидро"]},
    {"ticker": "YDEX", "name": "Яндекс", "market": "MOEX", "security_type": "stock", "sector": "Технологии", "currency": "RUB", "aliases": ["Яндекс"]},
    {"ticker": "VKCO", "name": "VK", "market": "MOEX", "security_type": "stock", "sector": "Технологии", "currency": "RUB", "aliases": ["VK"]},
    {"ticker": "MGNT", "name": "Магнит", "market": "MOEX", "security_type": "stock", "sector": "Ритейл", "currency": "RUB", "aliases": ["Магнит"]},
    {"ticker": "FIVE", "name": "X5 Group", "market": "MOEX", "security_type": "stock", "sector": "Ритейл", "currency": "RUB", "aliases": ["X5 Group", "X5"]},
    {"ticker": "OZON", "name": "Ozon", "market": "MOEX", "security_type": "stock", "sector": "Ритейл", "currency": "RUB", "aliases": ["Ozon"]},
    {"ticker": "PHOR", "name": "Фосагро", "market": "MOEX", "security_type": "stock", "sector": "Химическая промышленность", "currency": "RUB", "aliases": ["Фосагро"]},
    {"ticker": "URKA", "name": "Уралкалий", "market": "MOEX", "security_type": "stock", "sector": "Химическая промышленность", "currency": "RUB", "aliases": ["Уралкалий"]},
    {"ticker": "AKRN", "name": "Акрон", "market": "MOEX", "security_type": "stock", "sector": "Химическая промышленность", "currency": "RUB", "aliases": ["Акрон"]},
    {"ticker": "MTSS", "name": "МТС", "market": "MOEX", "security_type": "stock", "sector": "Телеком", "currency": "RUB", "aliases": ["МТС"]},
    {"ticker": "RTKM", "name": "Ростелеком", "market": "MOEX", "security_type": "stock", "sector": "Телеком", "currency": "RUB", "aliases": ["Ростелеком"]},
    {"ticker": "PIKK", "name": "ПИК", "market": "MOEX", "security_type": "stock", "sector": "Девелопмент", "currency": "RUB", "aliases": ["ПИК", "ПИК-группа"]},
    {"ticker": "LSRG", "name": "ЛСР", "market": "MOEX", "security_type": "stock", "sector": "Девелопмент", "currency": "RUB", "aliases": ["ЛСР"]},
    {"ticker": "TRNFP", "name": "Транснефть", "market": "MOEX", "security_type": "stock", "sector": "Транспорт", "currency": "RUB", "aliases": ["Транснефть"]},
    {"ticker": "GLTR", "name": "Globaltrans", "market": "MOEX", "security_type": "stock", "sector": "Транспорт", "currency": "RUB", "aliases": ["Globaltrans", "Глобалтранс"]},
    {"ticker": "AVAZ", "name": "АвтоВАЗ", "market": "MOEX", "security_type": "stock", "sector": "Автопром", "currency": "RUB", "aliases": ["АвтоВАЗ", "LADA"]},
    {"ticker": "KMAZ", "name": "КамАЗ", "market": "MOEX", "security_type": "stock", "sector": "Автопром", "currency": "RUB", "aliases": ["КамАЗ"]},
    {"ticker": "MTLR", "name": "Мечел", "market": "MOEX", "security_type": "stock", "sector": "Угольная отрасль", "currency": "RUB", "aliases": ["Мечел"]},
    {"ticker": "RASP", "name": "Распадская", "market": "MOEX", "security_type": "stock", "sector": "Угольная отрасль", "currency": "RUB", "aliases": ["Распадская"]},
]
